# don't change the following 8 lines
baseURL = "./"
languageCode = "en-US"
defaultContentLanguage = "en"
theme = ["hugo-theme-relearn"]
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = "false"
uglyurls = "true"
enableEmoji = "true"
relativeURLs = true
canonifyURLs = false


################################ BEGIN EDITING ################################
# Display Title of the project
title = "Can't Code? No Problem"

[params]
# Author of the site, will be used in meta information
author.name = "James Hilving & Dylan Spille"
logo = "images/white-logo.svg"
# Select a color theme.
themeVariant = "Workshop"
# themeVariant = "Spotlight"
# themeVariant = "Demo"
# themeVariant = "UseCase"

# The banner text under Fortinet logo on the top left of the project. Better to be short.
logoBannerText = "Can't Code? No Problem"
################################# END EDITING #################################


# Small text under the title
#  logoBannerSubText = "Internal Only"

# Shows a checkmark for visited pages on the menu
showVisitedLinks = true
# Disable search function. It will hide search bar
disableSearch = false
# Javascript and CSS cache are automatically busted when new version of site is generated.
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
disableAssetsBusting = false
# Set this to true to disable copy-to-clipboard button for inline code.
disableInlineCopyToClipBoard = false
# A title for shortcuts in menu is set by default. Set this to true to disable it.
disableShortcutsTitle = false

# If set to false, a Home button will appear below the search bar on the menu.
# It is redirecting to the landing page of the current language if specified. (Default is "/")
disableLandingPageButton = true
# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = true
# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = false
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = false
# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"


landingPageName = "<i class='fas fa-home'></i> Home"



[outputs]
home = ["HTML", "RSS"]

[[menu.shortcuts]]
name = "<i class='fas fa-print'></i> Single Page View (for printing)"
url = "allpages.html"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-file-pdf'></i> Presentation PDF"
url = "Cant_Code_Presentation.pdf"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-vial'></i> FNDN - ThreatLab FortiDemo"
url = "https://fndn.fortinet.net/index.php?/fortidemo/instances/"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-file'></i> Lab CSV Document"
url = "/docs/fortisoar-workshop-fortimail-users.csv"
weight = 8

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> System Config Doc"
url = "https://docs.fortinet.com/document/fortisoar/latest/administration-guide/304946/system-configuration#System_Configuration"
weight = 9

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> Fortinet FSR Docs"
url = "https://docs.fortinet.com/product/fortisoar"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-eye'></i> See the Content Hub"
url = "https://fortisoar.contenthub.fortinet.com/"
weight = 11

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
hrefTargetBlank = true
